from alembic.config import Config
from sqlalchemy.engine import Connection as Connection
from sqlalchemy.engine import Engine as Engine

def configuration(connection: Connection | None = None) -> Config: ...
def head_revision() -> str | None: ...
def current_revision(engine: Engine) -> str | None: ...
def upgrade(engine: Engine) -> None: ...
