from typing import Protocol

from _typeshed import Incomplete

from .config import WeComArchiveConfig as WeComArchiveConfig
from .models import EncryptedChat as EncryptedChat

class MissingKeyError(ValueError):
    """消息需要的密钥版本未配置。"""

class ArchiveClient(Protocol):
    def initialize(self) -> None: ...
    def set_private_key(self, pem: str | bytes, version: int) -> None: ...
    def key_versions(self) -> set[int]: ...
    def fetch(self, cursor: int) -> list[EncryptedChat]: ...
    def decrypt(self, chat: EncryptedChat) -> str: ...
    def close(self) -> None: ...

class FinanceClient:
    config: Incomplete
    def __init__(self, config: WeComArchiveConfig) -> None: ...
    def set_private_key(self, pem: str | bytes, version: int = 1) -> None: ...
    def key_versions(self) -> set[int]: ...
    def initialize(self) -> None: ...
    def fetch(self, cursor: int) -> list[EncryptedChat]: ...
    def decrypt(self, chat: EncryptedChat) -> str: ...
    def close(self) -> None: ...
