from collections.abc import Collection, Sequence
from typing import Literal, overload

from _typeshed import Incomplete

from .db import ConsumerTask as ConsumerTask
from .db import Database as Database
from .db import DecryptedMessage as DecryptedMessage
from .db import EncryptedMessage as EncryptedMessage
from .db import ParsedMessage as ParsedMessage
from .db import Progress as Progress
from .models import ConsumerMessage as ConsumerMessage
from .models import EncryptedChat as EncryptedChat

class ArchiveStore:
    """单实例内数据库操作串行；任务领取先提交，耗时工作在事务外执行。"""

    db: Incomplete
    def __init__(self, database: Database) -> None: ...
    def cursor(self) -> int: ...
    def save_batch(self, chats: Sequence[EncryptedChat]) -> None: ...
    def recover(self, versions: Collection[int]) -> None: ...
    @overload
    def claim(self, stage: Literal["decrypt"]) -> EncryptedChat | None: ...
    @overload
    def claim(self, stage: Literal["parse"]) -> tuple[str, str] | None: ...
    def decrypted(self, chat: EncryptedChat, raw_text: str) -> None: ...
    def parsed(self, message: ConsumerMessage) -> None: ...
    def fail(
        self, stage: Literal["decrypt", "parse"], msgid: str, status: str, error: str | None
    ) -> None: ...
    def sequence(self, msgid: str) -> int: ...
    def claim_consumer(
        self, names: Sequence[str], window: float
    ) -> tuple[str, ConsumerMessage] | None: ...
    def finish_consumer(
        self, name: str, msgid: str, status: str, error: str | None = None
    ) -> None: ...
