import abc
from _thread import RLock
from abc import ABC, abstractmethod
from threading import Event
from typing import Generic, TypeVar

from _typeshed import Incomplete

from ..config import ServiceConfig as ServiceConfig

log: Incomplete
TaskT = TypeVar("TaskT")

class Service(ABC, Generic[TaskT], metaclass=abc.ABCMeta):
    """领取与停止共用闸门，停止后的进度快照不再增加。"""

    config: Incomplete
    def __init__(
        self, config: ServiceConfig, stop_event: Event | None = None, gate: RLock | None = None
    ) -> None: ...
    @property
    def remaining(self) -> int: ...
    def is_stopping(self) -> bool: ...
    def wait(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def join(self) -> None: ...
    def after_task(self) -> None: ...
    @abstractmethod
    def acquire(self) -> TaskT | None: ...
    @abstractmethod
    def process(self, task: TaskT) -> None: ...
